name: 'ONO-FE 이슈 생성'
description: 'ONO-FE Repo에 이슈를 생성합니다.'
labels: []
title: '이슈 이름을 작성해주세요'
body:
  - type: input
    id: description
    attributes:
      label: '이슈 내용(Description)'
      description: '이슈에 대해서 간략히 설명해주세요'
      placeholder: '이슈에 대한 설명을 간략히 작성해주세요'
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: '상세 내용(Details)'
      description: '이슈에 대해서 자세히 설명해주세요'
      placeholder: '상세 내용을 작성해주세요'
    validations:
      required: true
