export const ROUTER_PATH = {
  ROOT: '/',
  MAIN: '/',
  COMBINATIONS: '/combinations',
  COMBINATIONS_DETAIL: '/combinations/:id',
  COMBO_LIST: '/combo-list',
  COMBO_DETAIL: '/combo-detail/:id',
  COMMUNITY: '/community',
  COMMUNITY_CREATE: '/community/create',
  COMMUNITY_DETAIL: '/community/:id',
  EVENT: '/event',
  MENU: '/menu',
  NEARBY: '/nearby',
  NEARBY_DETAIL: '/nearby/:id',
  POST_DETAIL: '/post-detail/:id',
  STORE_MAP: '/store-map',
};
